program sgeti_test; 
#include( "stdlib.hhf" )
#includeOnce( "sockets.hhf" )

	
static
	quit		:dword := 0;
	hostIPadrs	:dword;
	s			:vServer_t;
	i			:int32;
	timeout		:thunk;
	calls		:dword := 0;
	
	ipAdrsStr	:str.strvar(256);
	cmdLine		:str.strvar(256);
	exmsg		:str.strvar(256);
	
	
	
	procedure connected;
		@nodisplay;
		@nostackalign;
		@noframe;
	var
		handle		:dword;
		bufIndex	:dword;
		object		:pointer to vServer_t;
		ipAdrs		:hla.sockaddr;
		
		buffer		:char[64];
		
	begin connected;

		push( ebp );
		mov( esp, ebp );
		sub( _vars_, esp );
		
		pushad();
		pushfd();
		
		mov( eax, handle );
		mov( esi, object );
		
		/*****************************************************************/
		
		// Testing socket.geti32
		
		try
		
			object.geti32( );
			if( eax <> 1 ) then
			
				raise($1011);
			
			endif;	
			
			object.geti32( );
			if( eax <> -2 ) then
			
				raise($1012);
			
			endif;	
			
			object.geti32( );
			if( eax <> -2147483648 ) then
			
				raise($1013);
			
			endif;	
			
			object.geti32( );
			if( eax <> 2147483647 ) then
			
				raise($1014);
			
			endif;


			
			try
			
				object.geti32( );

			  unprotected
			  
			  	// We we got to this point, we failed to raise a conversion error.
				
			  	raise($1005 );
				
			  exception( ex.ConversionError )
			  
			  	// Okay, we succeeded if we got this exception.
				
			  anyexception
			  
			  	// Anything else? Pass it on.
				
			  	raise($1006 );
				
			endtry;
			object.readLn( );	// Clean up after ourselves.
			
			
			try
			
				object.geti32( );

			  unprotected
			  
			  	// We we got to this point, we failed to raise an overflow error.
				
			  	raise($1015 );
				
			  exception( ex.ValueOutOfRange )
			  
			  	// Okay, we succeeded if we got this exception.
				
			  anyexception
			  
			  	// Anything else? Pass it on.
				
			  	raise($1016 );
				
			endtry;
			object.readLn( );
			stderr.put( "socket.geti32 succeeded!" nl );
			
		  anyexception
		  
			stderr.put
			( 
				nl nl 
				"***************************************************" nl
				"socket.geti32 failed! eax=", eax, nl
				"Data read did not match data expected in file" nl
				"***************************************************" nl
				nl 
			);
			stdout.put( "Press Enter to Continue: " );
			stdin.readLn();
			os.exitProcess(1);
			
		endtry;








		// Testing socket.geti16
		
		try
		

			object.geti16( );
			if( ax <> 0 ) then
			
				raise($1021);
			
			endif;	
			
			object.geti16( );
			if( ax <> 1 ) then
			
				raise($1022);
			
			endif;	
			
			object.geti16( );
			if( ax <> -1 ) then
			
				raise($1023);
			
			endif;	
			
			object.geti16( );
			if( ax <> -32768 ) then
			
				raise($1024);
			
			endif;	
			
			object.geti16( );
			if( ax <> 32767 ) then
			
				raise($1025);
			
			endif;
			
			try
			
				object.geti16( );

			  unprotected
			  
			  	// We we got to this point, we failed to raise an overflow error.
				
			  	raise($1026 );
				
			  exception( ex.ValueOutOfRange )
			  
			  	// Okay, we succeeded if we got this exception.
				
			  anyexception
			  
			  	// Anything else? Pass it on.
				
			  	raise($1027 );
				
			endtry;
			object.readLn( );
			stderr.put( "socket.geti16 succeeded!" nl );
			
		  anyexception
		  
			stderr.put
			( 
				nl nl 
				"***************************************************" nl
				"socket.geti16 failed! eax=", eax, nl
				"Data read did not match data expected in file" nl
				"***************************************************" nl
				nl 
			);
			stdout.put( "Press Enter to Continue: " );
			stdin.readLn();
			os.exitProcess(1);
			
		endtry;





		// Testing socket.geti8
		
		try
		
			object.geti8( );
			if( al <> 0 ) then
			
				raise($1031);
			
			endif;	
			
			object.geti8( );
			if( al <> 1 ) then
			
				raise($1032);
			
			endif;	
			
			object.geti8( );
			if( al <> -1 ) then
			
				raise($1033);
			
			endif;	
			
			object.geti8( );
			if( (type int8 al) <> -128 ) then
			
				raise($1034);
			
			endif;
			
			object.geti8( );
			if( al <> 127 ) then
			
				raise($1035);
			
			endif;
			
			try
			
				object.geti8( );

			  unprotected
			  
			  	// We we got to this point, we failed to raise an overflow error.
				
			  	raise($1036 );
				
			  exception( ex.ValueOutOfRange )
			  
			  	// Okay, we succeeded if we got this exception.
				
			  anyexception
			  
			  	// Anything else? Pass it on.
				
			  	raise($1037 );
				
			endtry;
			object.readLn( );
			stderr.put( "socket.geti8 succeeded!" nl );
			
		  anyexception
		  
			stderr.put
			( 
				nl nl 
				"***************************************************" nl
				"socket.geti8 failed! eax=", eax, nl
				"Data read did not match data expected in file" nl
				"***************************************************" nl
				nl 
			);
			stdout.put( "Press Enter to Continue: " );
			stdin.readLn();
			os.exitProcess(1);
			
		endtry;
			
		/*****************************************************************/
		
		object.close();
		mov( 1, quit );
		popfd();
		popad();
		leave();
		ret( _parms_ );
		
	end connected;
	
begin sgeti_test; 

	thunk timeout :=
		#{
			// On entry to thunk, EAX contains the address of the timeout
			// variable. Set this as desired for the timeout (2 seconds,
			// in this case).
			
			mov( 2, (type hla.timeval [eax]).tv_sec );
			stderr.put( "server", nl );
			
			// On the second call to this thunk, start the client application:
			
			cmp( calls, 1 );
			jne dontRunApp;
			
				#if( os.win32 )
				
					str.put
					(
						cmdLine,
						"cmd /C rclient socket_geti.data ",
						ipAdrsStr,
						" 9805"
					);
					stdout.put( "cmd=", cmdLine, "'" nl );
					
				#else
				
					str.put
					(
						cmdLine,
						"rclient.exe socket_geti.data ",
						ipAdrsStr,
						" 9805"
					);
					stdout.put( "cmd=", cmdLine, "'" nl );
					
				#endif
				os.bkgnd( cmdLine );
			
			dontRunApp:
			inc( calls );
			mov( quit, eax );
				
		}#;
	
	try
	
		mov( 0, i );
		s.create();
		
		sock.hostAdrs(); 
		mov( eax, hostIPadrs );
		sock.ipToStr( eax, ipAdrsStr );
		
		s.start
		( 
			hostIPadrs, 
			$9805, 
			timeout,
			&connected,
			0
		);
		
	  anyexception
	  
	  	ex.exceptionMsg( eax, exmsg );
	  	stdout.put( "Server Exception: ", exmsg, nl );
		fileio.close( s.handle );
		s.destroy();
		
	endtry;
	 
end sgeti_test; 
